import { useState } from 'react';
import { Alert, Button, Card, DatePicker, Descriptions, Drawer, Form, Input, InputNumber, Select, Space, Table, Tabs, Tag, message } from 'antd';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import dayjs from 'dayjs';
import { useTranslation } from 'react-i18next';
import { api, type Session } from '../api/client';
import { ManifestWorkspace } from './ManifestWorkspace';

type Trip={id:number;external_trip_no:string;vehicle_plate?:string;seal_no?:string;expected_at?:string;arrived_at?:string;status:string;unit_count:number;expected_piece_count:number;linked_piece_count:number};
type Unit={id:number;external_unit_no:string;unit_type:string;expected_piece_count?:number;status:string;linked_piece_count:number;driver_count:number;wave_count:number};
type Detail={trip:Trip&Record<string,unknown>;units:Unit[]};
const nextTrip:Record<string,string>={EXPECTED:'ARRIVED',ARRIVED:'UNLOADING',UNLOADING:'READY_FOR_SCAN',READY_FOR_SCAN:'CLOSED'};
const nextUnit:Record<string,string>={EXPECTED:'ARRIVED',ARRIVED:'OPENED',OPENED:'CLEARED'};

export function ArrivalWorkspace({session,station,serviceDate}:{session:Session;station:string;serviceDate:string}){
 const {t}=useTranslation();const cache=useQueryClient();const [createOpen,setCreateOpen]=useState(false);const [tripId,setTripId]=useState<number>();const [unitOpen,setUnitOpen]=useState(false);
 const trips=useQuery({queryKey:['arrival-trips',station,serviceDate],queryFn:()=>api<Trip[]>(`/ops/v1/arrival-trips?serviceDate=${serviceDate}`,session,{},station)});
 const detail=useQuery({queryKey:['arrival-trip',station,tripId],enabled:!!tripId,queryFn:()=>api<Detail>(`/ops/v1/arrival-trips/${tripId}`,session,{},station)});
 const refresh=async()=>Promise.all([cache.invalidateQueries({queryKey:['arrival-trips',station,serviceDate]}),cache.invalidateQueries({queryKey:['arrival-trip',station,tripId]})]);
 const command=useMutation({mutationFn:({path,body}:{path:string;body:unknown})=>api(path,session,{method:'POST',body:JSON.stringify(body)},station),onSuccess:async()=>{message.success(t('arrival.saved'));setCreateOpen(false);setUnitOpen(false);await refresh();},onError:(e:Error)=>message.error(e.message)});
 const arrival=<Space direction="vertical" style={{width:'100%'}} size="middle">{trips.error&&<Alert type="error" showIcon message={trips.error.message}/>}<Card title={t('arrival.title')} extra={<Button type="primary" onClick={()=>setCreateOpen(true)}>{t('arrival.create')}</Button>}><Alert type="info" showIcon message={t('arrival.boundary')}/><Table<Trip> rowKey="id" dataSource={trips.data??[]} pagination={false} onRow={row=>({onClick:()=>setTripId(row.id)})} columns={[{title:t('arrival.tripNo'),dataIndex:'external_trip_no'},{title:t('arrival.vehicle'),dataIndex:'vehicle_plate'},{title:t('arrival.expected'),dataIndex:'expected_at'},{title:t('common.status'),dataIndex:'status',render:v=><Tag>{v}</Tag>},{title:t('arrival.units'),dataIndex:'unit_count'},{title:t('arrival.pieces'),render:(_,r)=>`${r.linked_piece_count}/${r.expected_piece_count}`}]}/></Card></Space>;
 return <><Tabs items={[{key:'arrival',label:t('arrival.tab'),children:arrival},{key:'manifest',label:t('arrival.legacyManifest'),children:<ManifestWorkspace session={session} station={station}/>}]} />
  <Drawer width={640} open={!!tripId} onClose={()=>setTripId(undefined)} title={`${t('arrival.detail')} · ${detail.data?.trip.external_trip_no??''}`} extra={<Button onClick={()=>setUnitOpen(true)}>{t('arrival.addUnit')}</Button>}>{detail.error&&<Alert type="error" message={detail.error.message}/>} {detail.data&&<Space direction="vertical" style={{width:'100%'}}><Descriptions bordered size="small" column={2} items={Object.entries(detail.data.trip).slice(0,10).map(([key,value])=>({key,label:key,children:String(value??'—')}))}/>{nextTrip[detail.data.trip.status]&&<Button type="primary" onClick={()=>command.mutate({path:`/ops/v1/arrival-trips/${tripId}/state`,body:{targetStatus:nextTrip[detail.data!.trip.status],reason:'Operations arrival progression'}})}>{t('arrival.moveTo')} {nextTrip[detail.data.trip.status]}</Button>}<Table<Unit> rowKey="id" pagination={false} dataSource={detail.data.units} columns={[{title:t('arrival.unitNo'),dataIndex:'external_unit_no'},{title:t('arrival.unitType'),dataIndex:'unit_type'},{title:t('common.status'),dataIndex:'status'},{title:t('arrival.coverage'),render:(_,u)=>`${u.linked_piece_count} ${t('arrival.pieces')} · ${u.driver_count} ${t('arrival.drivers')}`},{title:t('common.action'),render:(_,u)=>nextUnit[u.status]?<Button size="small" onClick={()=>command.mutate({path:`/ops/v1/handling-units/${u.id}/state`,body:{targetStatus:nextUnit[u.status],reason:'Operations unit progression'}})}>{nextUnit[u.status]}</Button>:null}]}/></Space>}</Drawer>
  <Drawer width={480} open={createOpen} onClose={()=>setCreateOpen(false)} title={t('arrival.create')}><Form layout="vertical" onFinish={v=>command.mutate({path:'/ops/v1/arrival-trips',body:{...v,expectedAt:v.expectedAt?.toISOString()}})}><Form.Item name="externalTripNo" label={t('arrival.tripNo')} rules={[{required:true}]}><Input/></Form.Item><Form.Item name="vehiclePlate" label={t('arrival.vehicle')}><Input/></Form.Item><Form.Item name="sealNo" label={t('arrival.seal')}><Input/></Form.Item><Form.Item name="expectedAt" label={t('arrival.expected')} initialValue={dayjs(`${serviceDate}T08:00:00`)}><DatePicker showTime style={{width:'100%'}}/></Form.Item><Form.Item name="note" label={t('common.reason')}><Input.TextArea/></Form.Item><Button block type="primary" htmlType="submit">{t('common.save')}</Button></Form></Drawer>
  <Drawer width={480} open={unitOpen} onClose={()=>setUnitOpen(false)} title={t('arrival.addUnit')}><Form layout="vertical" onFinish={v=>command.mutate({path:`/ops/v1/arrival-trips/${tripId}/handling-units`,body:{...v,trackingNumbers:String(v.trackingNumbers??'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean)}})}><Form.Item name="externalUnitNo" label={t('arrival.unitNo')} rules={[{required:true}]}><Input/></Form.Item><Form.Item name="unitType" label={t('arrival.unitType')} initialValue="PALLET"><Select options={['PALLET','CAGE','BAG','LOOSE'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="expectedPieceCount" label={t('arrival.expectedPieces')}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="trackingNumbers" label={t('arrival.trackingList')}><Input.TextArea rows={6}/></Form.Item><Form.Item name="reason" label={t('common.reason')} rules={[{required:true}]}><Input.TextArea/></Form.Item><Button block type="primary" htmlType="submit">{t('common.save')}</Button></Form></Drawer>
 </>;
}
