import { useCallback, useMemo, useState } from 'react';
import { Alert, Button, Card, Drawer, Form, Input, InputNumber, List, Progress, Select, Space, Steps, Table, Tag, Typography, message } from 'antd';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, type Session } from '../api/client';
import { PlanningMap, type PlanningParcel } from './PlanningMap';
import { useTranslation } from 'react-i18next';

type Shift={driver_id:number;driver_name:string;driver_code:string;availability_status:string;parcel_capacity?:number;assigned_count:number};
type WaveResult={wave:{id:number;wave_code:string;status:string};drivers:Array<{task_id:number;driver_id:number;driver_name:string;parcel_count:number;parcel_capacity:number;remaining_capacity:number}>};

export function DispatchWorkspace({session,station,initialDate,initialFilter}:{session:Session;station:string;initialDate?:string;initialFilter?:string}){
 const {t}=useTranslation();const cache=useQueryClient();const serviceDate=initialDate!;const [stage,setStage]=useState(0);const [selected,setSelected]=useState<Set<number>>(new Set());const [focus,setFocus]=useState<PlanningParcel>();const [driver,setDriver]=useState<number>();const [areaVersion,setAreaVersion]=useState<number>();const [waveId,setWaveId]=useState<number>();const [capacityOpen,setCapacityOpen]=useState(false);const [listOpen,setListOpen]=useState(false);
 const parcels=useQuery({queryKey:['planning-parcels',station,serviceDate],queryFn:()=>api<PlanningParcel[]>(`/ops/v1/planning/parcels?serviceDate=${serviceDate}&limit=2000`,session,{},station)});
 const shifts=useQuery({queryKey:['planning-shifts',station,serviceDate],queryFn:()=>api<Shift[]>(`/ops/v1/planning/shifts?serviceDate=${serviceDate}`,session,{},station)});
 const wave=useQuery({queryKey:['planning-wave',station,waveId],enabled:!!waveId,queryFn:()=>api<WaveResult>(`/ops/v1/planning/waves/${waveId}`,session,{},station)});
 const refresh=async()=>Promise.all([cache.invalidateQueries({queryKey:['planning-parcels',station,serviceDate]}),cache.invalidateQueries({queryKey:['planning-shifts',station,serviceDate]}),cache.invalidateQueries({queryKey:['planning-wave',station,waveId]})]);
 const command=useMutation({mutationFn:({path,body}:{path:string;body:unknown})=>api(path,session,{method:'POST',body:JSON.stringify(body)},station),onSuccess:async()=>{message.success(t('dispatch.commandSuccess'));setSelected(new Set());await refresh();},onError:(e:Error)=>message.error(e.message)});
 const saveShift=useMutation({mutationFn:(value:{driverId:number;availabilityStatus:string;parcelCapacity:number})=>api('/ops/v1/planning/shifts',session,{method:'PUT',body:JSON.stringify({...value,serviceDate,note:'Operations planning'})},station),onSuccess:async()=>{message.success(t('dispatch.shiftSaved'));await refresh();}});
 const toggle=useCallback((id:number)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;}),[]);
 const all=useMemo(()=>parcels.data??[],[parcels.data]);const visible=useMemo(()=>initialFilter==='unmatched-area'?all.filter(p=>p.exception_code==='UNMATCHED_AREA'):initialFilter==='unassigned'?all.filter(p=>!p.driver_id&&!p.exception_code):all,[all,initialFilter]);const areas=useMemo(()=>Array.from(new Map(all.filter(p=>p.area_version_id).map(p=>[p.area_version_id!,{value:p.area_version_id!,label:p.area_code??String(p.area_version_id)}])).values()),[all]);const assigned=all.filter(p=>p.driver_id).length;const exceptions=all.filter(p=>p.exception_code).length;const available=(shifts.data??[]).filter(s=>s.availability_status==='AVAILABLE');const capacity=available.reduce((sum,s)=>sum+(s.parcel_capacity??0),0);const waveStatus=wave.data?.wave.status;
 const createWave=async(values:{waveCode:string;routeCode?:string})=>{const result=await api<{wave:{id:number}}|{id:number}>('/ops/v1/planning/waves',session,{method:'POST',body:JSON.stringify({...values,serviceDate})},station);setWaveId('wave'in result?result.wave.id:result.id);setStage(1);message.success(t('dispatch.waveCreated'));};
 const stepItems=[{title:t('dispatch.stageCapacity'),description:t('dispatch.capacitySummary',{drivers:available.length,capacity})},{title:t('dispatch.stageAssign'),description:t('dispatch.assignmentSummary',{assigned,total:all.length})},{title:t('dispatch.stageRelease'),description:waveStatus??t('dispatch.noDraft')}];
 return <div className="planning-console">
  <Card className="planning-stage-card"><Steps current={stage} onChange={setStage} items={stepItems}/><Space wrap className="planning-stage-actions"><Tag color="blue">{station}</Tag><Tag>{serviceDate}</Tag><Button onClick={()=>setCapacityOpen(true)}>{t('dispatch.manageCapacity')}</Button><Button onClick={()=>setListOpen(true)}>{t('dispatch.openWorklist')} ({visible.length})</Button></Space></Card>
  {(parcels.error||shifts.error||wave.error)&&<Alert type="error" showIcon message={(parcels.error??shifts.error??wave.error)?.message}/>} 
  {stage===0&&<Card title={t('dispatch.stageCapacity')} extra={<Button type="primary" disabled={!available.length||capacity<all.length-exceptions} onClick={()=>setStage(1)}>{t('dispatch.continueAssign')}</Button>}><Alert showIcon type={capacity>=all.length-exceptions?'success':'warning'} message={t('dispatch.capacityReadiness',{drivers:available.length,capacity,required:all.length-exceptions})}/><List grid={{gutter:12,column:3}} dataSource={shifts.data??[]} renderItem={s=><List.Item><Card size="small" title={s.driver_name} extra={<Tag color={s.availability_status==='AVAILABLE'?'green':'default'}>{s.availability_status}</Tag>}><Progress percent={s.parcel_capacity?Math.round(100*s.assigned_count/s.parcel_capacity):0}/><Typography.Text>{s.assigned_count}/{s.parcel_capacity??'—'}</Typography.Text></Card></List.Item>}/></Card>}
  {stage===1&&<div className="planning-grid"><section className="planning-map-panel"><PlanningMap station={station} parcels={visible} selected={selected} onToggle={toggle} onSelect={setFocus}/><div className="map-legend"><Tag color="blue">{t('dispatch.unassigned')}</Tag><Tag color="green">{t('dispatch.assigned')}</Tag><Tag color="orange">{t('dispatch.dataException')}</Tag></div></section><aside className="planning-sidebar"><Card title={waveId?t('dispatch.activeDraft'):t('dispatch.createPlan')}>
   {!waveId?<Form layout="vertical" onFinish={createWave}><Form.Item name="waveCode" label={t('dispatch.waveCode')} rules={[{required:true}]}><Input placeholder={`WAVE-${station}-${serviceDate}`}/></Form.Item><Form.Item name="routeCode" label={t('dispatch.routeCode')}><Input/></Form.Item><Button block type="primary" htmlType="submit">{t('dispatch.createDraft')}</Button></Form>:<Space direction="vertical" style={{width:'100%'}}><Typography.Title level={5}>{wave.data?.wave.wave_code}</Typography.Title><Tag>{waveStatus}</Tag><Select value={driver} onChange={setDriver} style={{width:'100%'}} placeholder={t('dispatch.driver')} options={available.map(s=>({value:s.driver_id,label:`${s.driver_name} · ${s.assigned_count}/${s.parcel_capacity}`}))}/><Button block type="primary" disabled={!driver||!selected.size||waveStatus!=='DRAFT'} onClick={()=>command.mutate({path:`/ops/v1/planning/waves/${waveId}/assignments`,body:{driverId:driver,parcelIds:[...selected],areaVersionIds:[],reason:'Map parcel assignment'}})}>{t('dispatch.assignSelected',{count:selected.size})}</Button><Select value={areaVersion} onChange={setAreaVersion} allowClear style={{width:'100%'}} placeholder={t('dispatch.area')} options={areas}/><Button block disabled={!driver||!areaVersion||waveStatus!=='DRAFT'} onClick={()=>command.mutate({path:`/ops/v1/planning/waves/${waveId}/assignments`,body:{driverId:driver,parcelIds:[],areaVersionIds:[areaVersion],reason:'Whole-area assignment'}})}>{t('dispatch.assignArea')}</Button><Button block onClick={()=>setStage(2)}>{t('dispatch.reviewRelease')}</Button></Space>}
  </Card></aside></div>}
  {stage===2&&<Card title={t('dispatch.stageRelease')} extra={<Button onClick={()=>setStage(1)}>{t('dispatch.backAssign')}</Button>}><Space direction="vertical" size="large" style={{width:'100%'}}><Alert showIcon type={exceptions||assigned<all.length-exceptions?'warning':'success'} message={t('dispatch.preflightSummary',{assigned,ready:all.length-exceptions,exceptions})}/><List header={t('dispatch.driverTasks')} bordered dataSource={wave.data?.drivers??[]} renderItem={item=><List.Item extra={<Tag color={item.remaining_capacity<0?'red':'green'}>{item.remaining_capacity} {t('dispatch.remaining')}</Tag>}><List.Item.Meta title={item.driver_name} description={`${item.parcel_count}/${item.parcel_capacity}`}/></List.Item>}/><Space><Button disabled={waveStatus!=='DRAFT'||assigned<all.length-exceptions} onClick={()=>command.mutate({path:`/ops/v1/planning/waves/${waveId}/freeze`,body:{reason:'Planning preflight approved'}})}>{t('dispatch.freeze')}</Button><Button type="primary" disabled={waveStatus!=='FROZEN'} onClick={()=>command.mutate({path:`/ops/v1/planning/waves/${waveId}/publish`,body:{reason:'Released to driver scan lists'}})}>{t('dispatch.publish')}</Button></Space></Space></Card>}
  <Drawer title={t('dispatch.capacity')} width={520} open={capacityOpen} onClose={()=>setCapacityOpen(false)}><Form layout="vertical" onFinish={v=>saveShift.mutate(v)}><Form.Item name="driverId" label={t('dispatch.driver')} rules={[{required:true}]}><Select options={(shifts.data??[]).map(s=>({value:s.driver_id,label:s.driver_name}))}/></Form.Item><Form.Item name="availabilityStatus" label={t('common.status')} initialValue="AVAILABLE"><Select options={['AVAILABLE','UNAVAILABLE'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="parcelCapacity" label={t('dispatch.capacity')} initialValue={25} rules={[{required:true}]}><InputNumber min={1} max={1000} style={{width:'100%'}}/></Form.Item><Button block type="primary" htmlType="submit">{t('dispatch.saveShift')}</Button></Form></Drawer>
  <Drawer title={t('dispatch.parcelList')} width={900} open={listOpen} onClose={()=>setListOpen(false)}><Table rowKey="parcel_id" size="small" dataSource={visible} pagination={{pageSize:20}} rowSelection={{selectedRowKeys:[...selected],onChange:keys=>setSelected(new Set(keys.map(Number)))}} onRow={row=>({onClick:()=>setFocus(row)})} columns={[{title:t('field.tracking_no'),dataIndex:'tracking_no'},{title:t('common.status'),dataIndex:'status'},{title:t('dispatch.area'),dataIndex:'area_code'},{title:t('dispatch.driver'),dataIndex:'driver_name'},{title:t('dispatch.exception'),dataIndex:'exception_code'}]}/></Drawer>
  <Drawer open={!!focus} onClose={()=>setFocus(undefined)} title={focus?.tracking_no}>{focus&&<><List dataSource={Object.entries(focus)} renderItem={([key,value])=><List.Item><Typography.Text type="secondary">{key}</Typography.Text><Typography.Text>{String(value??'—')}</Typography.Text></List.Item>}/>{focus.driver_id&&waveId&&<Space.Compact block><Select value={driver} onChange={setDriver} style={{width:'70%'}} options={available.map(s=>({value:s.driver_id,label:s.driver_name}))}/><Button disabled={!driver||driver===focus.driver_id} onClick={()=>command.mutate({path:`/ops/v1/planning/waves/${waveId}/parcels/${focus.parcel_id}/reassign`,body:{driverId:driver,reason:'Operator map reassignment'}})}>{t('dispatch.reassign')}</Button></Space.Compact>}</>}</Drawer>
 </div>;
}
