import { useCallback, useMemo, useState } from 'react';
import { Alert, Button, Card, Col, Drawer, Empty, Form, Input, InputNumber, Row, Select, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, type Session } from '../api/client';
import { PlanningMap, type PlanningParcel } from './PlanningMap';
import { useTranslation } from 'react-i18next';

type Area={id:number;area_code:string;area_name:string;status:string;version_id?:number;version_status?:string};

export function OrderReadinessWorkspace({session,station,serviceDate,initialFilter}:{session:Session;station:string;serviceDate:string;initialFilter?:string}){
 const {t}=useTranslation();const cache=useQueryClient();const [selected,setSelected]=useState<Set<number>>(new Set());const [focus,setFocus]=useState<PlanningParcel>();const [filter,setFilter]=useState(initialFilter??'all');
 const parcels=useQuery({queryKey:['planning-parcels',station,serviceDate],queryFn:()=>api<PlanningParcel[]>(`/ops/v1/planning/parcels?serviceDate=${serviceDate}&limit=2000`,session,{},station)});
 const areas=useQuery({queryKey:['areas',station],queryFn:()=>api<Area[]>('/ops/v1/delivery-areas',session,{},station)});
 const all=useMemo(()=>parcels.data??[],[parcels.data]);const missing=all.filter(p=>p.exception_code==='MISSING_GEOCODE');const unmatched=all.filter(p=>p.exception_code==='UNMATCHED_AREA');const ready=all.filter(p=>!p.exception_code);
 const visible=useMemo(()=>filter==='missing-geocode'?missing:filter==='unmatched-area'?unmatched:filter==='ready'?ready:all,[all,filter,missing,ready,unmatched]);
 const toggle=useCallback((id:number)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;}),[]);
 const action=useMutation({mutationFn:({path,body}:{path:string;body:unknown})=>api(path,session,{method:'POST',body:JSON.stringify(body)},station),onSuccess:async()=>{message.success(t('orders.resolved'));setFocus(undefined);await Promise.all([cache.invalidateQueries({queryKey:['planning-parcels',station,serviceDate]}),cache.invalidateQueries({queryKey:['control-tower',station,serviceDate]})]);},onError:(error:Error)=>message.error(error.message)});
 return <Space direction="vertical" style={{width:'100%'}} size="middle">
  {(parcels.error||areas.error)&&<Alert type="error" showIcon message={(parcels.error??areas.error)?.message}/>}<Card title={t('orders.title')}><Typography.Paragraph type="secondary">{t('orders.help')}</Typography.Paragraph><Row gutter={12}>{[['all',all.length,'orders.expected'],['ready',ready.length,'orders.ready'],['missing-geocode',missing.length,'orders.missing'],['unmatched-area',unmatched.length,'orders.unmatched']].map(([code,count,label])=><Col xs={12} md={6} key={String(code)}><Card hoverable className={filter===code?'metric-selected':''} onClick={()=>setFilter(String(code))}><Statistic title={t(String(label))} value={Number(count)} valueStyle={{color:String(code).includes('missing')||String(code).includes('unmatched')?'#cf1322':undefined}}/></Card></Col>)}</Row></Card>
  <div className="order-readiness-grid"><Card className="order-map-card"><PlanningMap station={station} parcels={visible} selected={selected} onToggle={toggle} onSelect={setFocus}/></Card><Card title={t('orders.queue')}><Table<PlanningParcel> size="small" rowKey="parcel_id" dataSource={visible} pagination={{pageSize:15}} onRow={row=>({onClick:()=>setFocus(row)})} columns={[{title:t('field.tracking_no'),dataIndex:'tracking_no'},{title:t('orders.address'),dataIndex:'address_line1'},{title:t('orders.postal'),dataIndex:'postal_code'},{title:t('dispatch.exception'),dataIndex:'exception_code',render:value=>value?<Tag color="orange">{value}</Tag>:<Tag color="green">READY</Tag>}]}/></Card></div>
  <Drawer width={520} open={!!focus} onClose={()=>setFocus(undefined)} title={`${t('orders.detail')} · ${focus?.tracking_no}`}>
   {focus?<Space direction="vertical" style={{width:'100%'}}><Card size="small"><p><b>{focus.recipient_name as string}</b></p><p>{focus.address_line1 as string}, {focus.city as string} {focus.postal_code as string}</p><Tag color="orange">{focus.exception_code??'READY'}</Tag></Card>
    {focus.exception_code==='MISSING_GEOCODE'&&<Card title={t('orders.coordinateFix')}><Form layout="vertical" onFinish={values=>action.mutate({path:`/ops/v1/parcels/${focus.parcel_id}/area-match`,body:{...values,providerCode:'OPERATOR',precisionCode:'MANUAL',confidence:1,normalizedAddress:String(focus.address_line1??''),reason:values.reason}})}><Form.Item name="longitude" label={t('orders.longitude')} rules={[{required:true}]}><InputNumber style={{width:'100%'}} min={-180} max={180} precision={7}/></Form.Item><Form.Item name="latitude" label={t('orders.latitude')} rules={[{required:true}]}><InputNumber style={{width:'100%'}} min={-90} max={90} precision={7}/></Form.Item><Form.Item name="reason" label={t('common.reason')} rules={[{required:true}]}><Input.TextArea/></Form.Item><Button block type="primary" htmlType="submit">{t('orders.geocodeAndMatch')}</Button></Form></Card>}
    {focus.exception_code&&<Card title={t('orders.manualArea')}><Form layout="vertical" onFinish={values=>action.mutate({path:`/ops/v1/parcels/${focus.parcel_id}/area-override`,body:values})}><Form.Item name="areaVersionId" label={t('dispatch.area')} rules={[{required:true}]}><Select options={(areas.data??[]).filter(a=>a.status==='ACTIVE'&&a.version_status==='PUBLISHED').map(a=>({value:a.version_id,label:`${a.area_code} · ${a.area_name}`}))}/></Form.Item><Form.Item name="reason" label={t('common.reason')} rules={[{required:true}]}><Input.TextArea/></Form.Item><Button block htmlType="submit">{t('orders.applyOverride')}</Button></Form></Card>}</Space>:<Empty/>}
  </Drawer>
 </Space>;
}
