import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Button, Empty, Space, Tag } from 'antd';
import { loadGoogleMaps, STATION_CENTERS } from './AreaMapEditor';

export type PlanningParcel={parcel_id:number;tracking_no:string;status?:string;longitude?:number;latitude?:number;exception_code?:string;driver_id?:number;driver_name?:string;area_code?:string;area_version_id?:number;[key:string]:unknown};

function pointColor(parcel:PlanningParcel,selected:boolean){if(selected)return '#722ed1';if(parcel.exception_code==='OPEN_CASE')return '#cf1322';if(parcel.exception_code)return '#d46b08';if(parcel.driver_id)return '#389e0d';return '#1677ff';}

export function PlanningMap({station,parcels,selected,onToggle,onSelect}:{station:string;parcels:PlanningParcel[];selected:Set<number>;onToggle:(id:number)=>void;onSelect:(parcel:PlanningParcel)=>void}){
 const node=useRef<HTMLDivElement>(null);const map=useRef<google.maps.Map|undefined>(undefined);const layer=useRef<google.maps.Data|undefined>(undefined);const click=useRef<google.maps.MapsEventListener|undefined>(undefined);const parcelRef=useRef<Map<number,PlanningParcel>>(new Map());const [ready,setReady]=useState(false);const [error,setError]=useState('');
 const key=import.meta.env.VITE_GOOGLE_MAPS_API_KEY?.trim();const byId=useMemo(()=>new Map(parcels.map(parcel=>[parcel.parcel_id,parcel])),[parcels]);
 useEffect(()=>{parcelRef.current=byId;},[byId]);
 const fitAll=useCallback(()=>{if(!map.current)return;const bounds=new google.maps.LatLngBounds();parcels.forEach(parcel=>{if(parcel.latitude!=null&&parcel.longitude!=null)bounds.extend({lat:Number(parcel.latitude),lng:Number(parcel.longitude)});});if(!bounds.isEmpty())map.current.fitBounds(bounds,48);},[parcels]);
 useEffect(()=>{if(!key||!node.current)return;let active=true;setError('');void loadGoogleMaps(key).then(({Map})=>{if(!active||!node.current)return;map.current=new Map(node.current,{center:STATION_CENTERS[station]??STATION_CENTERS['YHZ-01'],zoom:11,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,gestureHandling:'greedy',clickableIcons:false});layer.current=new google.maps.Data({map:map.current});click.current=layer.current.addListener('click',(event:google.maps.Data.MouseEvent)=>{const id=Number(event.feature.getProperty('parcelId'));const parcel=parcelRef.current.get(id);if(parcel){onToggle(id);onSelect(parcel);}});setReady(true);}).catch(()=>setError('Google Maps could not load. Open Areas to verify the shared map configuration.'));return()=>{active=false;click.current?.remove();layer.current?.setMap(null);map.current=undefined;layer.current=undefined;setReady(false);};},[key,onSelect,onToggle,station]);
 useEffect(()=>{if(!ready||!layer.current)return;layer.current.forEach(feature=>layer.current?.remove(feature));const features=parcels.filter(p=>p.latitude!=null&&p.longitude!=null).map(parcel=>({type:'Feature' as const,properties:{parcelId:parcel.parcel_id},geometry:{type:'Point' as const,coordinates:[Number(parcel.longitude),Number(parcel.latitude)]}}));layer.current.addGeoJson({type:'FeatureCollection',features});layer.current.setStyle(feature=>{const parcel=byId.get(Number(feature.getProperty('parcelId')))!;return {icon:{path:google.maps.SymbolPath.CIRCLE,scale:selected.has(parcel.parcel_id)?9:7,fillColor:pointColor(parcel,selected.has(parcel.parcel_id)),fillOpacity:.92,strokeColor:'#fff',strokeWeight:2},title:`${parcel.tracking_no}${parcel.driver_name?' · '+parcel.driver_name:''}`,zIndex:selected.has(parcel.parcel_id)?100:1};});fitAll();},[byId,fitAll,parcels,ready,selected]);
 const locatable=parcels.filter(p=>p.latitude!=null&&p.longitude!=null).length;
 if(!key)return <Alert type="warning" showIcon message="Google Maps API key is not configured"/>;
 return <div className="planning-map-wrap">{error&&<Alert type="error" showIcon message={error}/>}<div ref={node} className="planning-map" aria-label="Parcel planning map"/>{ready&&locatable===0&&<div className="map-empty"><Empty description={parcels.length?'All matching parcels are missing coordinates':'No parcels match the current filter'}/></div>}<Space className="map-status" wrap><Tag>Queried {parcels.length}</Tag><Tag color="green">Locatable {locatable}</Tag><Tag color={parcels.length-locatable?'orange':'default'}>Missing {parcels.length-locatable}</Tag><Tag color="blue">Displayed {ready?locatable:0}</Tag><Button size="small" onClick={fitAll} disabled={!ready||!locatable}>Fit all</Button></Space></div>;
}
