import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const SUPPORTED_LOCALES = ['en-CA', 'fr-CA', 'zh-CN'] as const;
export type SupportedLocale = typeof SUPPORTED_LOCALES[number];
export const translations: Record<SupportedLocale, Record<string, string>> = {
    'en-CA': {
        'app.title':'OpenDelivery Operations','auth.username':'Username','auth.password':'Password','auth.signIn':'Sign in','auth.signOut':'Sign out','auth.failed':'Login failed','locale.label':'Language','station.label':'Station','common.success':'Operation completed','common.action':'Action','common.status':'Status','common.reason':'Operational reason','common.confirm':'Confirm decision','common.notReady':'This pilot-critical workspace is connected in a later slice.',
        'nav.dashboard':'Dashboard','nav.areas':'Areas','nav.manifests':'Manifests','nav.dispatch':'Dispatch','nav.cases':'Cases','nav.callbacks':'Callbacks','nav.closeout':'Closeout',
        'areas.title':'Delivery areas','areas.import':'Import GeoJSON','areas.help':'Published polygons define reusable planning areas. Import GeoJSON, validate it, then publish it.','areas.validate':'Validate','areas.publish':'Publish','areas.dialog':'Import delivery area','areas.reason':'Change reason','areas.create':'Create draft','areas.success':'Area operation completed','areas.invalidJson':'GeoJSON is not valid JSON','areas.code':'Area code','areas.name':'Area name','areas.level':'Level','areas.version':'Version','areas.draft':'Draft','areas.geometry':'GeoJSON Feature, Polygon, or MultiPolygon',
        'manifest.title':'Inbound manifests','manifest.start':'Start receiving','manifest.close':'Close with case carryover','manifest.scanPlaceholder':'Scan tracking number','manifest.damaged':'Damaged','manifest.record':'Record scan','manifest.resolve':'Resolve','manifest.resolveTitle':'Resolve {{status}}','manifest.decision':'Decision: {{decision}}',
        'dispatch.create':'Create and publish wave','dispatch.waveCode':'Wave code','dispatch.routeCode':'Route code','dispatch.driver':'Driver','dispatch.inventory':'Dispatchable inventory','dispatch.recent':'Recent waves','dispatch.submit':'Publish {{count}} parcels','dispatch.success':'Wave created and published',
        'field.id':'ID','field.external_manifest_no':'Manifest number','field.expected_count':'Expected','field.received_count':'Received','field.discrepancy_count':'Discrepancies','field.expected_tracking_no':'Tracking number','field.receipt_status':'Receipt status','field.parcel_status':'Parcel status','field.discrepancy_reason':'Discrepancy reason','field.tracking_no':'Tracking number','field.route_code':'Route','field.driver_name':'Driver','field.driver_id':'Driver ID','field.wave_code':'Wave code','field.service_date':'Service date','field.promised_date':'Promised date','field.recipient_name':'Recipient','field.postal_code':'Postal code','field.task_count':'Tasks','field.parcel_count':'Parcels',
        'status.ACTIVE':'Active','status.DRAFT':'Draft','status.VALIDATED':'Validated','status.PUBLISHED':'Published','status.RETIRED':'Retired','status.EXPECTED':'Expected','status.RECEIVING':'Receiving','status.DISCREPANCY':'Discrepancy','status.CLOSED':'Closed',
    },
    'fr-CA': {
        'app.title':'Opérations OpenDelivery','auth.username':'Nom d’utilisateur','auth.password':'Mot de passe','auth.signIn':'Ouvrir une session','auth.signOut':'Fermer la session','auth.failed':'Échec de connexion','locale.label':'Langue','station.label':'Station','common.success':'Opération terminée','common.action':'Action','common.status':'État','common.reason':'Motif opérationnel','common.confirm':'Confirmer la décision','common.notReady':'Cet espace critique sera connecté dans une tranche ultérieure.',
        'nav.dashboard':'Tableau de bord','nav.areas':'Zones','nav.manifests':'Manifestes','nav.dispatch':'Répartition','nav.cases':'Dossiers','nav.callbacks':'Rappels','nav.closeout':'Clôture',
        'areas.title':'Zones de livraison','areas.import':'Importer GeoJSON','areas.help':'Les polygones publiés définissent les zones de planification. Importez, validez, puis publiez le GeoJSON.','areas.validate':'Valider','areas.publish':'Publier','areas.dialog':'Importer une zone','areas.reason':'Motif du changement','areas.create':'Créer le brouillon','areas.success':'Opération de zone terminée','areas.invalidJson':'Le GeoJSON n’est pas valide','areas.code':'Code de zone','areas.name':'Nom de zone','areas.level':'Niveau','areas.version':'Version','areas.draft':'Brouillon','areas.geometry':'Objet GeoJSON Feature, Polygon ou MultiPolygon',
        'manifest.title':'Manifestes entrants','manifest.start':'Commencer la réception','manifest.close':'Fermer avec report des dossiers','manifest.scanPlaceholder':'Numériser le numéro de suivi','manifest.damaged':'Endommagé','manifest.record':'Enregistrer le scan','manifest.resolve':'Résoudre','manifest.resolveTitle':'Résoudre {{status}}','manifest.decision':'Décision : {{decision}}',
        'dispatch.create':'Créer et publier une vague','dispatch.waveCode':'Code de vague','dispatch.routeCode':'Code de route','dispatch.driver':'Chauffeur','dispatch.inventory':'Inventaire répartissable','dispatch.recent':'Vagues récentes','dispatch.submit':'Publier {{count}} colis','dispatch.success':'Vague créée et publiée',
        'field.id':'ID','field.external_manifest_no':'Numéro de manifeste','field.expected_count':'Prévus','field.received_count':'Reçus','field.discrepancy_count':'Écarts','field.expected_tracking_no':'Numéro de suivi','field.receipt_status':'État de réception','field.parcel_status':'État du colis','field.discrepancy_reason':'Motif de l’écart','field.tracking_no':'Numéro de suivi','field.route_code':'Route','field.driver_name':'Chauffeur','field.driver_id':'ID chauffeur','field.wave_code':'Code de vague','field.service_date':'Date de service','field.promised_date':'Date promise','field.recipient_name':'Destinataire','field.postal_code':'Code postal','field.task_count':'Tâches','field.parcel_count':'Colis',
        'status.ACTIVE':'Actif','status.DRAFT':'Brouillon','status.VALIDATED':'Validé','status.PUBLISHED':'Publié','status.RETIRED':'Retiré','status.EXPECTED':'Attendu','status.RECEIVING':'Réception','status.DISCREPANCY':'Écart','status.CLOSED':'Fermé',
    },
    'zh-CN': {
        'app.title':'OpenDelivery 运营系统','auth.username':'用户名','auth.password':'密码','auth.signIn':'登录','auth.signOut':'退出登录','auth.failed':'登录失败','locale.label':'语言','station.label':'站点','common.success':'操作完成','common.action':'操作','common.status':'状态','common.reason':'运营处理原因','common.confirm':'确认处理','common.notReady':'此试运营关键工作台将在后续切片接入。',
        'nav.dashboard':'运营看板','nav.areas':'派送区域','nav.manifests':'到货清单','nav.dispatch':'派送计划','nav.cases':'异常工单','nav.callbacks':'上游回调','nav.closeout':'日终关站',
        'areas.title':'派送区域','areas.import':'导入 GeoJSON','areas.help':'已发布多边形用于本站派送规划。导入 GeoJSON，校验通过后再发布。','areas.validate':'校验','areas.publish':'发布','areas.dialog':'导入派送区域','areas.reason':'变更原因','areas.create':'创建草稿','areas.success':'区域操作完成','areas.invalidJson':'GeoJSON 不是有效 JSON','areas.code':'区域编码','areas.name':'区域名称','areas.level':'层级','areas.version':'版本','areas.draft':'草稿','areas.geometry':'GeoJSON Feature、Polygon 或 MultiPolygon',
        'manifest.title':'上游到货清单','manifest.start':'开始接收','manifest.close':'结转工单并关闭','manifest.scanPlaceholder':'扫描包裹追踪号','manifest.damaged':'破损','manifest.record':'记录扫描','manifest.resolve':'处理','manifest.resolveTitle':'处理 {{status}}','manifest.decision':'处理决定：{{decision}}',
        'dispatch.create':'创建并发布派送批次','dispatch.waveCode':'批次编码','dispatch.routeCode':'路线编码','dispatch.driver':'司机','dispatch.inventory':'可派送包裹','dispatch.recent':'最近批次','dispatch.submit':'发布 {{count}} 个包裹','dispatch.success':'派送批次已创建并发布',
        'field.id':'ID','field.external_manifest_no':'清单编号','field.expected_count':'预计数量','field.received_count':'已接收','field.discrepancy_count':'差异数量','field.expected_tracking_no':'追踪号','field.receipt_status':'接收状态','field.parcel_status':'包裹状态','field.discrepancy_reason':'差异原因','field.tracking_no':'追踪号','field.route_code':'路线','field.driver_name':'司机','field.driver_id':'司机 ID','field.wave_code':'批次编码','field.service_date':'派送日期','field.promised_date':'承诺日期','field.recipient_name':'收件人','field.postal_code':'邮编','field.task_count':'任务数','field.parcel_count':'包裹数',
        'status.ACTIVE':'启用','status.DRAFT':'草稿','status.VALIDATED':'已校验','status.PUBLISHED':'已发布','status.RETIRED':'已停用','status.EXPECTED':'待接收','status.RECEIVING':'接收中','status.DISCREPANCY':'存在差异','status.CLOSED':'已关闭',
    },
};
const resources=Object.fromEntries(SUPPORTED_LOCALES.map((locale)=>[locale,{translation:translations[locale]}]));
const stored=localStorage.getItem('opendelivery.locale');
const initial=SUPPORTED_LOCALES.includes(stored as SupportedLocale)?stored!:'en-CA';
void i18n.use(initReactI18next).init({resources,lng:initial,fallbackLng:'en-CA',interpolation:{escapeValue:false}});
export async function changeLocale(locale:SupportedLocale){localStorage.setItem('opendelivery.locale',locale);await i18n.changeLanguage(locale);}
export default i18n;
