CREATE TABLE upstream_partner (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    partner_code VARCHAR(64) NOT NULL,
    partner_name VARCHAR(160) NOT NULL,
    integration_mode VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    config_json JSON NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_partner_code (partner_code),
    CONSTRAINT ck_partner_mode CHECK (integration_mode IN ('PUSH', 'PULL', 'FILE', 'HYBRID')),
    CONSTRAINT ck_partner_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DISABLED'))
) ENGINE=InnoDB;

CREATE TABLE station (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    station_code VARCHAR(64) NOT NULL,
    station_name VARCHAR(160) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    address_line VARCHAR(255) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_station_code (station_code),
    CONSTRAINT ck_station_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'))
) ENGINE=InnoDB;

CREATE TABLE driver (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    home_station_id BIGINT UNSIGNED NULL,
    credential_id VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    driver_name VARCHAR(160) NOT NULL,
    phone VARCHAR(40) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_driver_credential (credential_id),
    KEY idx_driver_station_status (home_station_id, status),
    CONSTRAINT fk_driver_station FOREIGN KEY (home_station_id) REFERENCES station (id),
    CONSTRAINT ck_driver_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE'))
) ENGINE=InnoDB;

CREATE TABLE auth_session (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    driver_id BIGINT UNSIGNED NOT NULL,
    access_token_hash CHAR(64) NOT NULL,
    refresh_token_hash CHAR(64) NOT NULL,
    access_expires_at DATETIME(3) NOT NULL,
    refresh_expires_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_session_access_hash (access_token_hash),
    UNIQUE KEY uk_session_refresh_hash (refresh_token_hash),
    KEY idx_session_driver_active (driver_id, revoked_at),
    CONSTRAINT fk_session_driver FOREIGN KEY (driver_id) REFERENCES driver (id)
) ENGINE=InnoDB;

CREATE TABLE ingestion_batch (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    partner_id BIGINT UNSIGNED NOT NULL,
    external_batch_no VARCHAR(128) NULL,
    source_type VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'RECEIVED',
    received_count INT UNSIGNED NOT NULL DEFAULT 0,
    accepted_count INT UNSIGNED NOT NULL DEFAULT 0,
    rejected_count INT UNSIGNED NOT NULL DEFAULT 0,
    started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ingestion_external_batch (partner_id, external_batch_no),
    KEY idx_ingestion_partner_status_time (partner_id, status, started_at),
    CONSTRAINT fk_ingestion_partner FOREIGN KEY (partner_id) REFERENCES upstream_partner (id),
    CONSTRAINT ck_ingestion_source CHECK (source_type IN ('PUSH', 'PULL', 'FILE')),
    CONSTRAINT ck_ingestion_status CHECK (status IN ('RECEIVED', 'PROCESSING', 'PARTIAL', 'COMPLETED', 'FAILED'))
) ENGINE=InnoDB;

CREATE TABLE ingestion_record (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_id BIGINT UNSIGNED NOT NULL,
    partner_id BIGINT UNSIGNED NOT NULL,
    external_event_id VARCHAR(160) NOT NULL,
    external_waybill_no VARCHAR(128) NULL,
    payload_json JSON NOT NULL,
    payload_sha256 CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'RECEIVED',
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    processed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ingestion_event (partner_id, external_event_id),
    KEY idx_ingestion_record_batch_status (batch_id, status),
    CONSTRAINT fk_ingestion_record_batch FOREIGN KEY (batch_id) REFERENCES ingestion_batch (id),
    CONSTRAINT fk_ingestion_record_partner FOREIGN KEY (partner_id) REFERENCES upstream_partner (id),
    CONSTRAINT ck_ingestion_record_status CHECK (status IN ('RECEIVED', 'ACCEPTED', 'REJECTED', 'QUARANTINED'))
) ENGINE=InnoDB;

CREATE TABLE waybill (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    partner_id BIGINT UNSIGNED NOT NULL,
    external_waybill_no VARCHAR(128) NOT NULL,
    external_version VARCHAR(64) NULL,
    shipper_name VARCHAR(160) NULL,
    recipient_name VARCHAR(160) NOT NULL,
    recipient_phone VARCHAR(40) NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255) NULL,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NULL,
    postal_code VARCHAR(32) NOT NULL,
    country_code CHAR(2) NOT NULL DEFAULT 'CA',
    service_code VARCHAR(64) NULL,
    delivery_window_start DATETIME(3) NULL,
    delivery_window_end DATETIME(3) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    source_event_time DATETIME(3) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_waybill_partner_external (partner_id, external_waybill_no),
    KEY idx_waybill_postal_status (postal_code, status),
    CONSTRAINT fk_waybill_partner FOREIGN KEY (partner_id) REFERENCES upstream_partner (id),
    CONSTRAINT ck_waybill_status CHECK (status IN ('ACTIVE', 'ON_HOLD', 'CANCELLED', 'COMPLETED'))
) ENGINE=InnoDB;

CREATE TABLE parcel (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    waybill_id BIGINT UNSIGNED NOT NULL,
    tracking_no VARCHAR(128) NOT NULL,
    piece_no SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    piece_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    current_station_id BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    current_custody_type VARCHAR(24) NOT NULL DEFAULT 'UPSTREAM',
    current_custody_id BIGINT UNSIGNED NULL,
    current_location_code VARCHAR(128) NULL,
    route_code VARCHAR(64) NULL,
    promised_date DATE NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_parcel_tracking (tracking_no),
    UNIQUE KEY uk_parcel_waybill_piece (waybill_id, piece_no),
    KEY idx_parcel_station_status_updated (current_station_id, status, updated_at),
    KEY idx_parcel_route_date (route_code, promised_date),
    CONSTRAINT fk_parcel_waybill FOREIGN KEY (waybill_id) REFERENCES waybill (id),
    CONSTRAINT fk_parcel_station FOREIGN KEY (current_station_id) REFERENCES station (id),
    CONSTRAINT ck_parcel_piece CHECK (piece_no > 0 AND piece_count >= piece_no),
    CONSTRAINT ck_parcel_status CHECK (status IN ('RECEIVED', 'AT_STATION', 'SORTED', 'READY_FOR_DISPATCH', 'ASSIGNED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELIVERY_FAILED', 'RESCHEDULED', 'RETURN_PENDING', 'RETURNED_TO_STATION', 'RETURNED_TO_UPSTREAM', 'CANCELLED', 'LOST', 'DAMAGED', 'ADDRESS_EXCEPTION')),
    CONSTRAINT ck_parcel_custody CHECK (current_custody_type IN ('UPSTREAM', 'STATION', 'DRIVER', 'RETURN_CARRIER', 'UNKNOWN'))
) ENGINE=InnoDB;

CREATE TABLE parcel_status_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    parcel_id BIGINT UNSIGNED NOT NULL,
    sequence_no BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    reason_code VARCHAR(64) NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    actor_type VARCHAR(24) NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    metadata_json JSON NULL,
    occurred_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_parcel_event_sequence (parcel_id, sequence_no),
    UNIQUE KEY uk_parcel_event_idempotency (parcel_id, idempotency_key),
    KEY idx_parcel_event_time (parcel_id, occurred_at),
    CONSTRAINT fk_parcel_event_parcel FOREIGN KEY (parcel_id) REFERENCES parcel (id)
) ENGINE=InnoDB;

CREATE TABLE custody_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    parcel_id BIGINT UNSIGNED NOT NULL,
    from_type VARCHAR(24) NULL,
    from_id BIGINT UNSIGNED NULL,
    to_type VARCHAR(24) NOT NULL,
    to_id BIGINT UNSIGNED NULL,
    reason_code VARCHAR(64) NOT NULL,
    reference_type VARCHAR(32) NULL,
    reference_id BIGINT UNSIGNED NULL,
    actor_id BIGINT UNSIGNED NULL,
    occurred_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_custody_parcel_time (parcel_id, occurred_at),
    KEY idx_custody_target (to_type, to_id, occurred_at),
    CONSTRAINT fk_custody_parcel FOREIGN KEY (parcel_id) REFERENCES parcel (id)
) ENGINE=InnoDB;

CREATE TABLE inbound_manifest (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    partner_id BIGINT UNSIGNED NOT NULL,
    station_id BIGINT UNSIGNED NOT NULL,
    external_manifest_no VARCHAR(128) NOT NULL,
    expected_arrival_at DATETIME(3) NULL,
    actual_arrival_at DATETIME(3) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'EXPECTED',
    expected_count INT UNSIGNED NOT NULL DEFAULT 0,
    received_count INT UNSIGNED NOT NULL DEFAULT 0,
    discrepancy_count INT UNSIGNED NOT NULL DEFAULT 0,
    closed_by BIGINT UNSIGNED NULL,
    closed_at DATETIME(3) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_manifest_partner_external (partner_id, external_manifest_no),
    KEY idx_manifest_station_status_arrival (station_id, status, expected_arrival_at),
    CONSTRAINT fk_manifest_partner FOREIGN KEY (partner_id) REFERENCES upstream_partner (id),
    CONSTRAINT fk_manifest_station FOREIGN KEY (station_id) REFERENCES station (id),
    CONSTRAINT ck_manifest_status CHECK (status IN ('EXPECTED', 'RECEIVING', 'DISCREPANCY', 'CLOSED', 'CANCELLED'))
) ENGINE=InnoDB;

CREATE TABLE inbound_manifest_item (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    manifest_id BIGINT UNSIGNED NOT NULL,
    parcel_id BIGINT UNSIGNED NULL,
    expected_tracking_no VARCHAR(128) NOT NULL,
    receipt_status VARCHAR(24) NOT NULL DEFAULT 'EXPECTED',
    received_at DATETIME(3) NULL,
    received_by BIGINT UNSIGNED NULL,
    discrepancy_reason VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_manifest_tracking (manifest_id, expected_tracking_no),
    KEY idx_manifest_item_status (manifest_id, receipt_status),
    CONSTRAINT fk_manifest_item_manifest FOREIGN KEY (manifest_id) REFERENCES inbound_manifest (id),
    CONSTRAINT fk_manifest_item_parcel FOREIGN KEY (parcel_id) REFERENCES parcel (id),
    CONSTRAINT ck_manifest_item_status CHECK (receipt_status IN ('EXPECTED', 'RECEIVED', 'MISSING', 'EXTRA', 'WRONG_STATION', 'DAMAGED'))
) ENGINE=InnoDB;

CREATE TABLE dispatch_wave (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    station_id BIGINT UNSIGNED NOT NULL,
    wave_code VARCHAR(80) NOT NULL,
    service_date DATE NOT NULL,
    route_code VARCHAR(64) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    published_at DATETIME(3) NULL,
    published_by BIGINT UNSIGNED NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_wave_station_code (station_id, wave_code),
    KEY idx_wave_station_date_status (station_id, service_date, status),
    CONSTRAINT fk_wave_station FOREIGN KEY (station_id) REFERENCES station (id),
    CONSTRAINT ck_wave_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'IN_PROGRESS', 'CLOSED', 'CANCELLED'))
) ENGINE=InnoDB;

CREATE TABLE driver_task (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    wave_id BIGINT UNSIGNED NOT NULL,
    driver_id BIGINT UNSIGNED NOT NULL,
    station_id BIGINT UNSIGNED NOT NULL,
    task_code VARCHAR(80) NOT NULL,
    service_date DATE NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    accepted_at DATETIME(3) NULL,
    started_at DATETIME(3) NULL,
    closed_at DATETIME(3) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_code (task_code),
    KEY idx_task_driver_status_date (driver_id, status, service_date),
    KEY idx_task_wave_status (wave_id, status),
    CONSTRAINT fk_task_wave FOREIGN KEY (wave_id) REFERENCES dispatch_wave (id),
    CONSTRAINT fk_task_driver FOREIGN KEY (driver_id) REFERENCES driver (id),
    CONSTRAINT fk_task_station FOREIGN KEY (station_id) REFERENCES station (id),
    CONSTRAINT ck_task_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ACCEPTING', 'IN_PROGRESS', 'CLOSED', 'CANCELLED'))
) ENGINE=InnoDB;

CREATE TABLE driver_task_item (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    task_id BIGINT UNSIGNED NOT NULL,
    parcel_id BIGINT UNSIGNED NOT NULL,
    stop_sequence INT UNSIGNED NULL,
    item_status VARCHAR(24) NOT NULL DEFAULT 'ASSIGNED',
    active_slot TINYINT GENERATED ALWAYS AS (CASE WHEN item_status IN ('ASSIGNED', 'LOADED', 'OUT_FOR_DELIVERY') THEN 1 ELSE NULL END) STORED,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_parcel (task_id, parcel_id),
    UNIQUE KEY uk_parcel_active_task (parcel_id, active_slot),
    KEY idx_task_item_status (task_id, item_status),
    CONSTRAINT fk_task_item_task FOREIGN KEY (task_id) REFERENCES driver_task (id),
    CONSTRAINT fk_task_item_parcel FOREIGN KEY (parcel_id) REFERENCES parcel (id),
    CONSTRAINT ck_task_item_status CHECK (item_status IN ('ASSIGNED', 'LOADED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'RETURNED', 'REASSIGNED', 'CANCELLED'))
) ENGINE=InnoDB;

CREATE TABLE scan_session (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    task_id BIGINT UNSIGNED NOT NULL,
    driver_id BIGINT UNSIGNED NOT NULL,
    session_type VARCHAR(24) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    expected_count INT UNSIGNED NOT NULL DEFAULT 0,
    scanned_count INT UNSIGNED NOT NULL DEFAULT 0,
    discrepancy_count INT UNSIGNED NOT NULL DEFAULT 0,
    opened_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    submitted_at DATETIME(3) NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    reviewed_at DATETIME(3) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_scan_session_driver_status (driver_id, status, opened_at),
    KEY idx_scan_session_task_type (task_id, session_type),
    CONSTRAINT fk_scan_session_task FOREIGN KEY (task_id) REFERENCES driver_task (id),
    CONSTRAINT fk_scan_session_driver FOREIGN KEY (driver_id) REFERENCES driver (id),
    CONSTRAINT ck_scan_session_type CHECK (session_type IN ('LOAD', 'RETURN', 'TRANSFER')),
    CONSTRAINT ck_scan_session_status CHECK (status IN ('OPEN', 'SUBMITTED', 'APPROVED', 'REJECTED'))
) ENGINE=InnoDB;

CREATE TABLE scan_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    session_id BIGINT UNSIGNED NOT NULL,
    parcel_id BIGINT UNSIGNED NULL,
    tracking_no VARCHAR(128) NOT NULL,
    device_event_id VARCHAR(160) NOT NULL,
    result_code VARCHAR(24) NOT NULL,
    latitude DECIMAL(10, 7) NULL,
    longitude DECIMAL(10, 7) NULL,
    scanned_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_scan_device_event (device_event_id),
    KEY idx_scan_session_time (session_id, scanned_at),
    KEY idx_scan_tracking_time (tracking_no, scanned_at),
    CONSTRAINT fk_scan_event_session FOREIGN KEY (session_id) REFERENCES scan_session (id),
    CONSTRAINT fk_scan_event_parcel FOREIGN KEY (parcel_id) REFERENCES parcel (id),
    CONSTRAINT ck_scan_result CHECK (result_code IN ('EXPECTED', 'EXTRA', 'DUPLICATE', 'WRONG_TASK', 'UNKNOWN'))
) ENGINE=InnoDB;

CREATE TABLE delivery_attempt (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    task_item_id BIGINT UNSIGNED NOT NULL,
    parcel_id BIGINT UNSIGNED NOT NULL,
    driver_id BIGINT UNSIGNED NOT NULL,
    attempt_no SMALLINT UNSIGNED NOT NULL,
    outcome VARCHAR(24) NOT NULL,
    failure_reason_code VARCHAR(64) NULL,
    recipient_name VARCHAR(160) NULL,
    latitude DECIMAL(10, 7) NULL,
    longitude DECIMAL(10, 7) NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    attempted_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_attempt_parcel_no (parcel_id, attempt_no),
    UNIQUE KEY uk_attempt_idempotency (driver_id, idempotency_key),
    KEY idx_attempt_task_item (task_item_id, attempted_at),
    CONSTRAINT fk_attempt_task_item FOREIGN KEY (task_item_id) REFERENCES driver_task_item (id),
    CONSTRAINT fk_attempt_parcel FOREIGN KEY (parcel_id) REFERENCES parcel (id),
    CONSTRAINT fk_attempt_driver FOREIGN KEY (driver_id) REFERENCES driver (id),
    CONSTRAINT ck_attempt_outcome CHECK (outcome IN ('DELIVERED', 'FAILED'))
) ENGINE=InnoDB;

CREATE TABLE proof_of_delivery (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    attempt_id BIGINT UNSIGNED NOT NULL,
    pod_type VARCHAR(24) NOT NULL,
    object_uri VARCHAR(1000) NULL,
    content_sha256 CHAR(64) NULL,
    content_type VARCHAR(120) NULL,
    content_size BIGINT UNSIGNED NULL,
    captured_at DATETIME(3) NOT NULL,
    metadata_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_pod_attempt_type (attempt_id, pod_type),
    CONSTRAINT fk_pod_attempt FOREIGN KEY (attempt_id) REFERENCES delivery_attempt (id),
    CONSTRAINT ck_pod_type CHECK (pod_type IN ('PHOTO', 'SIGNATURE', 'OTP', 'RECIPIENT', 'GEOLOCATION'))
) ENGINE=InnoDB;

CREATE TABLE operational_case (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    case_no VARCHAR(80) NOT NULL,
    case_type VARCHAR(40) NOT NULL,
    parcel_id BIGINT UNSIGNED NULL,
    station_id BIGINT UNSIGNED NULL,
    priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    owner_type VARCHAR(24) NULL,
    owner_id BIGINT UNSIGNED NULL,
    sla_due_at DATETIME(3) NULL,
    resolution_code VARCHAR(64) NULL,
    resolution_note VARCHAR(1000) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    resolved_at DATETIME(3) NULL,
    closed_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_case_no (case_no),
    KEY idx_case_queue (status, owner_type, owner_id, sla_due_at),
    KEY idx_case_parcel_status (parcel_id, status),
    CONSTRAINT fk_case_parcel FOREIGN KEY (parcel_id) REFERENCES parcel (id),
    CONSTRAINT fk_case_station FOREIGN KEY (station_id) REFERENCES station (id),
    CONSTRAINT ck_case_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_case_status CHECK (status IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_EXTERNAL', 'RESOLVED', 'CLOSED'))
) ENGINE=InnoDB;

CREATE TABLE case_action (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    case_id BIGINT UNSIGNED NOT NULL,
    action_type VARCHAR(40) NOT NULL,
    from_status VARCHAR(24) NULL,
    to_status VARCHAR(24) NULL,
    actor_type VARCHAR(24) NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    note VARCHAR(1000) NULL,
    metadata_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_case_action_time (case_id, created_at),
    CONSTRAINT fk_case_action_case FOREIGN KEY (case_id) REFERENCES operational_case (id)
) ENGINE=InnoDB;

CREATE TABLE outbox_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    aggregate_type VARCHAR(40) NOT NULL,
    aggregate_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    event_key VARCHAR(160) NOT NULL,
    partner_id BIGINT UNSIGNED NULL,
    payload_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    locked_at DATETIME(3) NULL,
    locked_by VARCHAR(128) NULL,
    acknowledged_at DATETIME(3) NULL,
    last_error VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_outbox_event_key (event_key),
    KEY idx_outbox_dispatch (status, next_attempt_at, id),
    CONSTRAINT fk_outbox_partner FOREIGN KEY (partner_id) REFERENCES upstream_partner (id),
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING', 'SENDING', 'ACKNOWLEDGED', 'RETRY', 'DEAD_LETTER', 'WAIVED'))
) ENGINE=InnoDB;

CREATE TABLE callback_attempt (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    outbox_event_id BIGINT UNSIGNED NOT NULL,
    attempt_no INT UNSIGNED NOT NULL,
    request_url VARCHAR(1000) NOT NULL,
    request_sha256 CHAR(64) NOT NULL,
    response_status INT NULL,
    response_body_excerpt VARCHAR(2000) NULL,
    outcome VARCHAR(24) NOT NULL,
    error_message VARCHAR(1000) NULL,
    started_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_callback_attempt_no (outbox_event_id, attempt_no),
    CONSTRAINT fk_callback_outbox FOREIGN KEY (outbox_event_id) REFERENCES outbox_event (id),
    CONSTRAINT ck_callback_outcome CHECK (outcome IN ('SENDING', 'ACKNOWLEDGED', 'RETRY', 'FAILED'))
) ENGINE=InnoDB;

CREATE TABLE daily_reconciliation (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    station_id BIGINT UNSIGNED NOT NULL,
    business_date DATE NOT NULL,
    opening_count INT NOT NULL DEFAULT 0,
    inbound_count INT NOT NULL DEFAULT 0,
    transfer_in_count INT NOT NULL DEFAULT 0,
    dispatched_count INT NOT NULL DEFAULT 0,
    driver_return_count INT NOT NULL DEFAULT 0,
    delivered_count INT NOT NULL DEFAULT 0,
    transfer_out_count INT NOT NULL DEFAULT 0,
    upstream_return_count INT NOT NULL DEFAULT 0,
    expected_closing_count INT NOT NULL DEFAULT 0,
    actual_closing_count INT NOT NULL DEFAULT 0,
    variance_count INT NOT NULL DEFAULT 0,
    open_case_count INT NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    carryover_reason VARCHAR(1000) NULL,
    signed_off_by BIGINT UNSIGNED NULL,
    signed_off_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_reconciliation_station_date (station_id, business_date),
    KEY idx_reconciliation_status_date (status, business_date),
    CONSTRAINT fk_reconciliation_station FOREIGN KEY (station_id) REFERENCES station (id),
    CONSTRAINT ck_reconciliation_status CHECK (status IN ('OPEN', 'BALANCED', 'SIGNED_OFF', 'CARRIED_OVER'))
) ENGINE=InnoDB;
