spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
opendelivery.security.upstream-api-key=test-upstream-key
opendelivery.security.operations-api-key=test-operations-key
